PortoAlegrePlus/Models/Reclamacao.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PortoAlegrePlus.Models
{
    public class Reclamacao
    {
        public int ReclamacaoID { get; set; }

        [Display(Name = "Autor")]
        public string UsuarioID { get; set; }

        [Required]
        [Display(Name = "Título")]
        [StringLength(40, MinimumLength = 3)]
        public string Titulo { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Descrição")]
        [StringLength(100, MinimumLength = 5)]
        public string Descricao { get; set; }

        [Required]
        [Display(Name = "Data")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = false)]
        public DateTime DataReclamacao { get; set; }

        [Required]
        [Display(Name = "Endereço")]
        [StringLength(100, MinimumLength = 5)]
        public string Endereco { get; set; }

        [Display(Name = "Imagem")]
        public byte[] ImageFile { get; set; }
        public string ImageMimeType { get; set; }

        public string Status { get; set; }

        [Display(Name = "Resolvida? ")]
        public bool StatusUsuario { get; set; }

        [Display(Name = "Encerrada? ")]
        public bool StatusOficial { get; set; }

        public int CategoriaID { get; set; }
        public virtual Categoria Categoria { get; set; }

        public int BairroID { get; set; }
        public virtual Bairro Bairro { get; set; }

        public virtual ICollection<Comentario> Comentarios { get; set; }
    }
}

PortoAlegrePlus/Controllers/ReclamacaoController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PortoAlegrePlus.Models;
using Microsoft.AspNet.Identity;

namespace PortoAlegrePlus.Controllers
{
    public class ReclamacaoController : Controller
    {
        private PortoAlegrePlusDBContext db = new PortoAlegrePlusDBContext();

        public ActionResult Index(int? categoriaSelecionada, int? bairroSelecionado, String DataInicio, String DataFim, String statusSelecionado)
        {
            var reclamacoes = db.Reclamacoes.Include(r => r.Bairro).Include(r => r.Categoria);
            String usuario = "visitante";

            foreach (var item in reclamacoes)

                if (item.StatusOficial)
                {
                    item.Status = "Encerrada";
                }
                else if (item.StatusUsuario)
                {
                    item.Status = "Resolvida";
                }
                else
                {
                    item.Status = "Aberta";
                }

            db.SaveChanges();

            reclamacoes = FiltrarReclamacoes(usuario, categoriaSelecionada, bairroSelecionado, DataInicio, DataFim, statusSelecionado);

            return View(reclamacoes.OrderByDescending(a => a.DataReclamacao).ToList());
        }

        [Authorize]
        public ActionResult MinhasReclamacoes(int? categoriaSelecionada, int? bairroSelecionado, String DataInicio, String DataFim, String statusSelecionado)
        {

            string usuario = User.Identity.GetUserName();
            var reclamacoes = FiltrarReclamacoes(usuario, categoriaSelecionada, bairroSelecionado, DataInicio, DataFim, statusSelecionado);

            foreach (var item in reclamacoes)

                if (item.StatusOficial)
                {
                    item.Status = "Encerrada";
                }
                else if (item.StatusUsuario)
                {
                    item.Status = "Resolvida";
                }
                else
                {
                    item.Status = "Aberta";
                }

            db.SaveChanges();

            return View(reclamacoes.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reclamacao reclamacao = db.Reclamacoes.Find(id);

            if (reclamacao == null)
            {
                return HttpNotFound();
            }

            foreach (var item in reclamacao.Comentarios)
            {
                if (item.StatusUsuario)
                {
                    reclamacao.StatusUsuario = true;
                    reclamacao.Status = "Resolvida";
                }
            }

            var reclamacoes = db.Reclamacoes;
            foreach (var item in reclamacoes)
            {
                if (item.StatusOficial)
                {
                    item.Status = "Encerrada";
                }
            }

            db.SaveChanges();
            return View(reclamacao);
        }

        [Authorize]
        public ActionResult Create()
        {
            ViewBag.BairroID = new SelectList(db.Bairros, "BairroID", "Nome");
            ViewBag.CategoriaID = new SelectList(db.Categorias, "CategoriaID", "Nome");
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReclamacaoID,UsuarioID,Titulo,Descricao,DataReclamacao,Endereco,Status,StatusUsuario,StatusOficial,CategoriaID,BairroID")] Reclamacao reclamacao, HttpPostedFileBase image)
        {

            if (!(User.IsInRole("Contas Oficiais")))
            {

                if (ModelState.IsValid)
                {

                    if (image != null)
                    {
                        reclamacao.ImageMimeType = image.ContentType;
                        reclamacao.ImageFile = new byte[image.ContentLength];
                        image.InputStream.Read(reclamacao.ImageFile, 0, image.ContentLength);
                    }

                    reclamacao.UsuarioID = User.Identity.Name;
                    db.Reclamacoes.Add(reclamacao);
                    db.SaveChanges();
                    return RedirectToAction("MinhasReclamacoes");
                }

                ViewBag.BairroID = new SelectList(db.Bairros, "BairroID", "Nome", reclamacao.BairroID);
                ViewBag.CategoriaID = new SelectList(db.Categorias, "CategoriaID", "Nome", reclamacao.CategoriaID);
                return View(reclamacao);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            string usuario = User.Identity.GetUserName();
            Reclamacao reclamacao = db.Reclamacoes.Find(id);
            if (reclamacao == null || !(usuario == reclamacao.UsuarioID))
            {
                return HttpNotFound();
            }
            ViewBag.BairroID = new SelectList(db.Bairros, "BairroID", "Nome", reclamacao.BairroID);
            ViewBag.CategoriaID = new SelectList(db.Categorias, "CategoriaID", "Nome", reclamacao.CategoriaID);
            return View(reclamacao);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReclamacaoID,UsuarioID,Titulo,Descricao,DataReclamacao,Endereco,Status,StatusUsuario,StatusOficial,CategoriaID,BairroID")] Reclamacao reclamacao, HttpPostedFileBase image)
        {

            if (reclamacao.Status != "Encerrada")
            {

                if (ModelState.IsValid)
                {

                    if (image != null)
                    {
                        reclamacao.ImageMimeType = image.ContentType;
                        reclamacao.ImageFile = new byte[image.ContentLength];
                        image.InputStream.Read(reclamacao.ImageFile, 0, image.ContentLength);
                    }

                    reclamacao.UsuarioID = User.Identity.Name;
                    db.Entry(reclamacao).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("MinhasReclamacoes");

                }

                ViewBag.BairroID = new SelectList(db.Bairros, "BairroID", "Nome", reclamacao.BairroID);
                ViewBag.CategoriaID = new SelectList(db.Categorias, "CategoriaID", "Nome", reclamacao.CategoriaID);
                return View(reclamacao);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reclamacao reclamacao = db.Reclamacoes.Find(id);
            if (reclamacao == null)
            {
                return HttpNotFound();
            }
            return View(reclamacao);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reclamacao reclamacao = db.Reclamacoes.Find(id);
            db.Reclamacoes.Remove(reclamacao);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult GetImage(int id)
        {
            Reclamacao reclamacao = db.Reclamacoes.Find(id);
            if (reclamacao != null && reclamacao.ImageFile != null)
            {
                return File(reclamacao.ImageFile, reclamacao.ImageMimeType);
            }
            else
            {
                return new FilePathResult("~/Imagens/nao-disponivel.jpg", "image/jpeg");
            }
        }

        [Authorize]
        public ActionResult CriarComentario(int id)
        {
            return RedirectToAction("Create", "Comentario", new { id });
        }

        [Authorize(Roles = "Contas Oficiais")]
        public ActionResult EncerrarReclamacao(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reclamacao reclamacao = db.Reclamacoes.Find(id);
            if (reclamacao == null)
            {
                return HttpNotFound();
            }
            return View(reclamacao);
        }

        [Authorize(Roles = "Contas Oficiais")]
        [HttpPost, ActionName("EncerrarReclamacao")]
        [ValidateAntiForgeryToken]
        public ActionResult EncerrarReclamacaoConfirmed(int id)
        {

            if (User.IsInRole("Contas Oficiais"))
            {
                Reclamacao reclamacao = db.Reclamacoes.Find(id);

                reclamacao.StatusOficial = true;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        private IQueryable<Reclamacao> FiltrarReclamacoes(String usuario, int? categoriaSelecionada, int? bairroSelecionado, string DataInicio, String DataFim, String statusSelecionado)
        {


PortoAlegrePlus/Views/Reclamacao/Create.cshtml
@model PortoAlegrePlus.Models.Reclamacao

@{
    ViewBag.Title = "Reclamação";
}

<div class="container body-content">
    <h2>Criar Reclamação</h2>

    @using (Html.BeginForm("Create", "Reclamacao",
                                                FormMethod.Post,
                                                new { enctype = "multipart/form-data" }))

    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Reclamação</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CategoriaID, "Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CategoriaID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoriaID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control", rows = "9" } })
                    @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DataReclamacao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DataReclamacao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DataReclamacao, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BairroID, "Bairro", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("BairroID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BairroID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" class="form-control" name="Image" style="background-color:#222222" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Criar Reclamação" class="btn btn-success" />
                    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-success" })
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PortoAlegrePlus/Views/Reclamacao/Delete.cshtml
@model PortoAlegrePlus.Models.Reclamacao

@{
    ViewBag.Title = "Reclamação";
}

<div class="container body-content">
    <h2>Remover</h2>

    <h3>Tem certeza que deseja remover?</h3>
    <div>
        <h4>Reclamação</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Bairro.Nome)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Bairro.Nome)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Categoria.Nome)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Categoria.Nome)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Titulo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Titulo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Descricao)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Descricao)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DataReclamacao)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DataReclamacao)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Endereco)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Endereco)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Status)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Remover" class="btn btn-success" />
                @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-success" })
            </div>
        }
    </div>
</div>

PortoAlegrePlus/Views/Reclamacao/Details.cshtml
@model PortoAlegrePlus.Models.Reclamacao

@{
    ViewBag.Title = "Reclamação";
}

<div class="container body-content">
    <h2>Detalhes</h2>

    <div>
        <h4>Reclamação</h4>
        <hr />

        <div class="row">
            <div class="col-lg-5">

                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Titulo)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Titulo)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.UsuarioID)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.UsuarioID)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Categoria.Nome)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Categoria.Nome)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Descricao)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Descricao)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DataReclamacao)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DataReclamacao)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Bairro.Nome)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Bairro.Nome)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Endereco)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Endereco)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Status)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Status)
                    </dd>
                </dl>
            </div>
            <div class="col-lg-5">
                <img width="300" src="@Url.Action("GetImage", "Reclamacao", new {id=Model.ReclamacaoID})" />
            </div>
        </div>
    </div>

    <h2>Comentários</h2>

    @foreach (var item in Model.Comentarios)
    {
        <section class="comment-list">
            <article class="row">
                <div class="col-md-10 col-sm-10">
                    <div class="panel panel-default arrow left">
                        <div class="panel-body">
                            <header class="text-left">
                                <div class="comment-user"><i class="fa fa-user"></i> @item.UserNameID</div>
                                <time class="comment-date"><i class="fa fa-clock-o"></i> @item.DataComentario.ToShortDateString()</time>
                            </header>
                            <div class="comment-post">
                                <p>
                                    @item.Conteudo
                                </p>
                                @if (item.ImageFile != null)
                                {
                                    <br />
                                    <img width="250" src="@Url.Action("GetImage", "Comentario", new { id = item.ComentarioID })" />
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </article>
        </section>
    }

    <br />

    @if (!(User.IsInRole("Admin")) & Model.Status != "Encerrada")
    {

        @Html.ActionLink("Adicionar Comentário", "CriarComentario", new { id = Model.ReclamacaoID }, new { @class = "btn btn-success" })<label style="padding:4px"></label>
        if (User.Identity.Name == Model.UsuarioID)
        {
            @Html.ActionLink("Editar", "Edit", new { id = Model.ReclamacaoID }, new { @class = "btn btn-success" })<label style="padding:4px"></label>
        }
    }

    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-success" })

</div>

PortoAlegrePlus/Views/Reclamacao/Edit.cshtml
@model PortoAlegrePlus.Models.Reclamacao

@{
    ViewBag.Title = "Reclamação";
}

<div class="container body-content">
    <h2>Editar</h2>

    @using (Html.BeginForm("Edit", "Reclamacao",
                                                                                            FormMethod.Post,
                                                                                            new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Reclamação</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ReclamacaoID)

            <div class="form-group">
                @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CategoriaID, "Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CategoriaID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoriaID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control", rows = "9" } })
                    @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DataReclamacao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DataReclamacao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DataReclamacao, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BairroID, "Bairro", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("BairroID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BairroID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" class="form-control" name="Image" style="background-color:#222222" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StatusUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox-inline form-control" style="background-color:#222222">
                        @Html.EditorFor(model => model.StatusUsuario)
                        @Html.ValidationMessageFor(model => model.StatusUsuario, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Enviar" class="btn btn-success" />
                    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-sucess" })
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PortoAlegrePlus/Views/Reclamacao/EncerrarReclamacao.cshtml
@model PortoAlegrePlus.Models.Reclamacao

@{
    ViewBag.Title = "Reclamação";
}

<div class="container body-content">
    <h2>Encerrar Reclamação</h2>

    <h3>Tem certeza que deseja encerrar essa reclamação?</h3>
    <div>
        <h4>Reclamação</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Titulo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Titulo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UsuarioID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UsuarioID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Categoria.Nome)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Categoria.Nome)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Descricao)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Descricao)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DataReclamacao)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DataReclamacao)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Bairro.Nome)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Bairro.Nome)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Endereco)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Endereco)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Status)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Encerrar Reclamação" class="btn btn-success" />
                @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-success" })
            </div>
        }
    </div>
</div>