PortoAlegrePlus/Models/Comentario.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PortoAlegrePlus.Models
{
    public class Comentario
    {
        public int ComentarioID { get; set; }
        public int ReclamacaoID { get; set; }
        public string UserNameID { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Comentário")]
        [StringLength(100, MinimumLength = 3)]
        public string Conteudo { get; set; }

        public DateTime DataComentario { get; set; }

        [Display(Name = "Imagem")]
        public byte[] ImageFile { get; set; }
        public string ImageMimeType { get; set; }

        [Display(Name = "Resolvida? ")]
        public bool StatusUsuario { get; set; }

        public virtual Reclamacao Reclamacao { get; set; }

    }
}

PortoAlegrePlus/Controllers/ComentarioController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PortoAlegrePlus.Models;

namespace PortoAlegrePlus.Controllers
{
    [Authorize]
    public class ComentarioController : Controller
    {
        private PortoAlegrePlusDBContext db = new PortoAlegrePlusDBContext();

        public ActionResult Index()
        {
            var comentarios = db.Comentarios.Include(c => c.Reclamacao);
            return View(comentarios.ToList());
        }

        public ActionResult Create(int? id)
        {
            var modelo = new Comentario() { ComentarioID = (int)id, ReclamacaoID = (int)id };
            return View(modelo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ComentarioID,ReclamacaoID,UserNameID,Conteudo,DataComentario,StatusUsuario")] Comentario comentario, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    comentario.ImageMimeType = image.ContentType;
                    comentario.ImageFile = new byte[image.ContentLength];
                    image.InputStream.Read(comentario.ImageFile, 0, image.ContentLength);
                }

                comentario.DataComentario = DateTime.Now;
                comentario.UserNameID = User.Identity.Name;
                db.Comentarios.Add(comentario);
                db.SaveChanges();
                return RedirectToAction("Details", "Reclamacao", new { ID = comentario.ReclamacaoID });
            }

            ViewBag.ReclamacaoID = new SelectList(db.Reclamacoes, "ReclamacaoID", "Titulo", comentario.ReclamacaoID);
            return View(comentario);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comentario comentario = db.Comentarios.Find(id);
            if (comentario == null)
            {
                return HttpNotFound();
            }
            return View(comentario);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comentario comentario = db.Comentarios.Find(id);
            db.Comentarios.Remove(comentario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult GetImage(int id)
        {
            Comentario come = db.Comentarios.Find(id);
            if (come != null && come.ImageFile != null)
            {
                return File(come.ImageFile, come.ImageMimeType);
            }
            else
            {
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PortoAlegrePlus/Views/Comentario/Create.cshtml
@model PortoAlegrePlus.Models.Comentario

@{
    ViewBag.Title = "Comentário";
}

<div class="container body-content">
    <h2>Criar Comentário</h2>

    @using (Html.BeginForm("Create", "Comentario",
                                FormMethod.Post,
                                new { enctype = "multipart/form-data" }))

    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => Model.ReclamacaoID)

        <div class="form-horizontal">
            <h4>Comentário</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Conteudo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Conteudo, new { htmlAttributes = new { @class = "form-control", rows = "9" } })
                    @Html.ValidationMessageFor(model => model.Conteudo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    <input type="file" name="Image" />
                </div>
            </div>

            @if (!(User.IsInRole("Contas Oficiais")))
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.StatusUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox-inline">
                            @Html.EditorFor(model => model.StatusUsuario)
                            @Html.ValidationMessageFor(model => model.StatusUsuario, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            }

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Enviar" class="btn btn-success" />
                    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-success" })
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PortoAlegrePlus/Views/Comentario/Delete.cshtml
@model PortoAlegrePlus.Models.Comentario

@{
    ViewBag.Title = "Comentário";
}

<h2>Remover</h2>

<h3>Tem certeza que deseja remover este comentário? </h3>
<div>
    <h4>Comentario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Reclamacao.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reclamacao.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Conteudo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Conteudo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataComentario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataComentario)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Remover" class="btn btn-success" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>