PortoAlegrePlus/Models/Informacao.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PortoAlegrePlus.Models
{
    public class Informacao
    {
        [Display(Name = "Nome")]
        public String Nome { get; set; }

        [Display(Name = "Quantidade")]
        public int Quantidade { get; set; }

        [Display(Name = "Total de Reclamações")]
        public int TotalReclamacao { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.00}")]
        public double PercentualEncerrada { get; set; }

        [Display(Name = "Média de Comentários")]
        [DisplayFormat(DataFormatString = "{0:0.00}")]
        public double MediaComentarios { get; set; }

        [Display(Name = "% Status")]
        [DisplayFormat(DataFormatString = "{0:0.00}")]
        public double PercentualStatus { get; set; }

    }
}

PortoAlegrePlus/Controllers/InformacaoController.cs
using PortoAlegrePlus.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace PortoAlegrePlus.Controllers
{

    [Authorize(Roles = "Admin")]
    public class InformacaoController : Controller
    {

        private PortoAlegrePlusDBContext db = new PortoAlegrePlusDBContext();
        public ViewResult Index()
        {
            return View();
        }

        public ActionResult DadosCategoria(string dataInicioCategoria, string dataFimCategoria, string statusCategoria)
        {

            if (!String.IsNullOrEmpty(dataInicioCategoria) && !String.IsNullOrEmpty(dataFimCategoria))
            {
                DateTime dataInicio = DateTime.Parse((string)dataInicioCategoria);
                DateTime dataFim = DateTime.Parse((string)dataFimCategoria);

                if (!String.IsNullOrEmpty(statusCategoria) && !statusCategoria.Equals("filtrar"))
                {
                    var dataFiltrada = from reclamacao in db.Reclamacoes.Where(c => c.DataReclamacao >= dataInicio && c.DataReclamacao <= dataFim)
                                       group reclamacao by reclamacao.Categoria into dateGroup
                                       select new Informacao()
                                       {
                                           Nome = dateGroup.Key.Nome,
                                           Quantidade = dateGroup.Count(),
                                           MediaComentarios = dateGroup.Average(g => g.Comentarios.Count),
                                           PercentualStatus = ((double)(dateGroup.Where(c => c.Status.Equals(statusCategoria)).Count()) / dateGroup.Count()) * 100,

                                       };
                    return PartialView(dataFiltrada.OrderBy(g => g.Quantidade).ToList());
                }
                else
                {
                    var dataFiltrada = from reclamacao in db.Reclamacoes.Where(c => c.DataReclamacao >= dataInicio && c.DataReclamacao <= dataFim)
                                       group reclamacao by reclamacao.Categoria into dateGroup
                                       select new Informacao()
                                       {
                                           Nome = dateGroup.Key.Nome,
                                           Quantidade = dateGroup.Count(),
                                           MediaComentarios = dateGroup.Average(g => g.Comentarios.Count),
                                           PercentualStatus = 0
                                       };
                    return PartialView(dataFiltrada.OrderBy(g => g.Quantidade).ToList());
                }
            }

            if (!String.IsNullOrEmpty(statusCategoria) && !statusCategoria.Equals("filtro"))
            {

                var dataFiltrada = from reclamacao in db.Reclamacoes
                                   group reclamacao by reclamacao.Categoria into dateGroup
                                   select new Informacao()
                                   {
                                       Nome = dateGroup.Key.Nome,
                                       Quantidade = dateGroup.Count(),
                                       MediaComentarios = dateGroup.Average(g => g.Comentarios.Count),
                                       PercentualStatus = ((double)(dateGroup.Where(c => c.Status.Equals(statusCategoria)).Count()) / dateGroup.Count()) * 100,
                                   };
                return PartialView(dataFiltrada);
            }

            var data = from reclamacao in db.Reclamacoes
                       group reclamacao by reclamacao.Categoria into dateGroup
                       select new Informacao()
                       {
                           Nome = dateGroup.Key.Nome,
                           Quantidade = dateGroup.Count(),
                           MediaComentarios = dateGroup.Average(g => g.Comentarios.Count),
                           PercentualStatus = 0
                       };

            return PartialView(data.ToList());
        }


        public ActionResult DadosBairro(string dataInicioBairro, string dataFimBairro, string statusBairro)
        {


            if (!String.IsNullOrEmpty(dataInicioBairro) && !String.IsNullOrEmpty(dataFimBairro))
            {
                DateTime dataInicio = DateTime.Parse((string)dataInicioBairro);
                DateTime dataFim = DateTime.Parse((string)dataFimBairro);

                if (!String.IsNullOrEmpty(statusBairro) && !statusBairro.Equals("filtrar"))
                {
                    var dataFiltrada = from reclamacao in db.Reclamacoes.Where(c => c.DataReclamacao >= dataInicio && c.DataReclamacao <= dataFim)
                                       group reclamacao by reclamacao.Bairro into dateGroup
                                       select new Informacao()
                                       {
                                           Nome = dateGroup.Key.Nome,
                                           Quantidade = dateGroup.Count(),
                                           MediaComentarios = dateGroup.Average(g => g.Comentarios.Count),
                                           PercentualStatus = ((double)(dateGroup.Where(c => c.Status.Equals(statusBairro)).Count()) / dateGroup.Count()) * 100,
                                       };
                    return PartialView(dataFiltrada.OrderBy(g => g.Quantidade).ToList());
                }
                else
                {
                    var dataFiltrada = from reclamacao in db.Reclamacoes.Where(c => c.DataReclamacao >= dataInicio && c.DataReclamacao <= dataFim)
                                       group reclamacao by reclamacao.Bairro into dateGroup
                                       select new Informacao()
                                       {
                                           Nome = dateGroup.Key.Nome,
                                           Quantidade = dateGroup.Count(),
                                           MediaComentarios = dateGroup.Average(g => g.Comentarios.Count),
                                           PercentualStatus = 0
                                       };
                    return PartialView(dataFiltrada.OrderBy(g => g.Quantidade).ToList());
                }
            }

            if (!String.IsNullOrEmpty(statusBairro) && !statusBairro.Equals("filtro"))
            {

                var dataFiltrada = from reclamacao in db.Reclamacoes
                                   group reclamacao by reclamacao.Bairro into dateGroup
                                   select new Informacao()
                                   {
                                       Nome = dateGroup.Key.Nome,
                                       Quantidade = dateGroup.Count(),
                                       MediaComentarios = dateGroup.Average(g => g.Comentarios.Count),
                                       PercentualStatus = ((double)(dateGroup.Where(c => c.Status.Equals(statusBairro)).Count()) / dateGroup.Count()) * 100,
                                   };
                return PartialView(dataFiltrada);
            }

            var data = from reclamacao in db.Reclamacoes
                       group reclamacao by reclamacao.Bairro into dateGroup
                       select new Informacao()
                       {
                           Nome = dateGroup.Key.Nome,
                           Quantidade = dateGroup.Count(),
                           MediaComentarios = dateGroup.Average(g => g.Comentarios.Count),
                           PercentualStatus = 0
                       };

            return PartialView(data.ToList());
        }

        public ActionResult DadosReclamacao()
        {
            var data = new Informacao()
            {
                TotalReclamacao = db.Reclamacoes.Count(),
                PercentualEncerrada = Math.Round(((double)(db.Reclamacoes.Where(c => c.Status.Equals("Encerrada")).Count()) / db.Reclamacoes.Count()) * 100),

            };

            return PartialView(data);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PortoAlegrePlus/Views/Informacao/DadosBairro.cshtml
@model IEnumerable<PortoAlegrePlus.Models.Informacao>

@{
    ViewBag.Title = "Informações";
}

<h3><span class="label label-success">Dados por Bairro</span></h3>

@using (Html.BeginForm())
{
    <div class="table-responsive" style="padding-bottom:20px">
        <table class="table">
            <thead>
                <tr>
                    <th>De</th>
                    <th>Até</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="col-md-4">
                        <input type="date" class="btn btn-default btn-sm" name="dataInicioBairro" value="">
                    </td>
                    <td class="col-md-4">
                        <input type="date" class="btn btn-default btn-sm" name="dataFimBairro" value="">
                    </td>
                    <td class="col-md-12">
                        <select name="statusBairro" class="btn btn-default btn-sm">
                            <option value="filtro">Escolher...</option>
                            <option value="Aberta">Aberta</option>
                            <option value="Resolvida">Resolvida</option>
                            <option value="Encerrada">Encerrada</option>
                        </select>
                        <input type="submit" class="btn btn-info btn-sm" value="Gerar">
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
}

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr class="success">
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantidade)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MediaComentarios)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PercentualStatus)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantidade)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MediaComentarios)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PercentualStatus) %
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

PortoAlegrePlus/Views/Informacao/DadosCategoria.cshtml
@model IEnumerable<PortoAlegrePlus.Models.Informacao>

@{
    ViewBag.Title = "Informações";
}

<h3><span class="label label-danger">Dados por Categoria</span></h3>

@using (Html.BeginForm())
{
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>De</th>
                    <th>Até</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="col-md-4">
                        <input type="date" class="btn btn-default btn-sm" name="dataInicioCategoria" value="">
                    </td>
                    <td class="col-md-4">
                        <input type="date" class="btn btn-default btn-sm" name="dataFimCategoria" value="">
                    </td>
                    <td class="col-md-12">
                        <select name="statusCategoria" class="btn btn-default btn-sm">
                            <option value="filtro">Escolher...</option>
                            <option value="Aberta">Aberta</option>
                            <option value="Resolvida">Resolvida</option>
                            <option value="Encerrada">Encerrada</option>
                        </select>
                        <input type="submit" class="btn btn-info btn-sm" value="Gerar">
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

}

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr class="danger">
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantidade)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MediaComentarios)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PercentualStatus)
                </th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantidade)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MediaComentarios)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PercentualStatus) %
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

PortoAlegrePlus/Views/Informacao/DadosReclamacao.cshtml
@model PortoAlegrePlus.Models.Informacao

@{
    ViewBag.Title = "Informacoes";
}

<h3 class="text-warning">Total de Reclamações = @Model.TotalReclamacao</h3>
<br />
<h3 class="text-warning">--> Percentual de Encerradas : @Model.PercentualEncerrada %</h3>

PortoAlegrePlus/Views/Informacao/Index.cshtml
@model IEnumerable<PortoAlegrePlus.Models.Informacao>

@{
    ViewBag.Title = "Relatórios";
}

<div class="container body-content">

    <h2>Relatórios</h2>
    <hr />

    @Html.Action("DadosReclamacao", "Informacao", null)
    <hr />

    @Html.Action("DadosCategoria", "Informacao", null)
    <hr />

    @Html.Action("DadosBairro", "Informacao", null)
</div>