PortoAlegrePlus/Controllers/RoleController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.EntityFramework;
using PortoAlegrePlus.Models;
using PortoAlegrePlus;
using Microsoft.AspNet.Identity;

namespace PortoAlegrePlus.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private ApplicationDbContext context = new ApplicationDbContext();

        public ActionResult Index()
        {
            return View(context.Roles.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                context.Roles.Add(new IdentityRole()
                {
                    Name = collection["RoleName"]
                });
                context.SaveChanges();
                ViewBag.ResultMessage = "Grupo de Usuários criado com sucesso!";
                return View("Create");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(string RoleName)
        {
            var thisRole = context.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            context.Roles.Remove(thisRole);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(string roleName)
        {
            var thisRole = context.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            return View(thisRole);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Microsoft.AspNet.Identity.EntityFramework.IdentityRole role)
        {
            try
            {
                context.Entry(role).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ManageUserRoles()
        {
            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RoleAddToUser(string UserName, string RoleName)
        {


            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(context));

            if (user != null)
            {
                manager.AddToRole(user.Id, RoleName);
                TempData["add"] = "<script>alert('O usuário foi adicionado ao grupo');</script>";
            }
            else
            {
                TempData["add"] = "<script>alert('Usuário não encontrado');</script>";
            }

            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;

            return View("ManageUserRoles");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetRoles(string UserName)
        {
            if (!string.IsNullOrWhiteSpace(UserName))
            {
                ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
                var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(context));

                if (user != null)
                {
                    ViewBag.RolesForThisUser = manager.GetRoles(user.Id);
                }
                else
                {
                    TempData["get"] = "<script>alert('Usuário não encontrado');</script>";
                }

                var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
                ViewBag.Roles = list;
            }

            return View("ManageUserRoles");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteRoleForUser(string UserName, string RoleName)
        {
            var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(context));

            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            if (user != null)
            {
                if (manager.IsInRole(user.Id, RoleName))
                {
                    manager.RemoveFromRole(user.Id, RoleName);
                    TempData["delete"] = "<script>alert('O usuário foi removido do grupo');</script>";
                }
                else
                {
                    TempData["delete"] = "<script>alert('Este usuário não pertence ao grupo selecionado');</script>";
                }
            }
            else
            {
                TempData["delete"] = "<script>alert('Usuário não encontrado');</script>";
            }

            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;
            return View("ManageUserRoles");

        }
    }
}

PortoAlegrePlus/Views/Role/Create.cshtml
@{
    ViewBag.Title = "Grupos de Usuários";
}

<div class="container body-content">
    <h2>Criar Grupo de Usuários</h2>

    @Html.ActionLink("Grupos de Usuários", "Index", null, new { @class = "btn btn-success" })  @Html.ActionLink("Gerenciar Grupo de Usuários", "ManageUserRoles", null, new { @class = "btn btn-success" })

    <hr />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <form>
            <div class="form-group">
                <label>Nome do Grupo de Usuários</label>
                @Html.TextBox("RoleName", null, new { @class = "form-control" })
            </div>
            <button type="submit" class="btn btn-success">Enviar</button>
        </form>
    }

    <p>
        @ViewBag.ResultMessage
    </p>
</div>

PortoAlegrePlus/Views/Role/Edit.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole

@{
    ViewBag.Title = "Grupos de Usuários";
}

<div class="container body-content">
    <h2>Renomear</h2>

    @Html.ActionLink("Grupos de Usuários", "Index", null, new { @class = "btn btn-success" }) @Html.ActionLink("Gerenciar Grupo de Usuários", "ManageUserRoles", null, new { @class = "btn btn-success" })
    <hr />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <form>
            <div class="form-group">
                <label>Nome do Grupo de Usuários</label>
                @Html.TextBoxFor(model => model.Name, null, new { @class = "form-control" })
            </div>
            <button type="submit" class="btn btn-success">Enviar</button>
        </form>
    }

</div>


PortoAlegrePlus/Views/Role/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Grupos de Usuários";
}

<div class="container body-content">
    <h2>Grupos de Usuários </h2>

    @Html.ActionLink("Criar Grupo de Usuários", "Create", null, new { @class = "btn btn-success" }) @Html.ActionLink("Gerenciar Grupo de Usuários", "ManageUserRoles", null, new { @class = "btn btn-success" })
    <hr />
    <div>
        @foreach (var role in Model)
        {
            <table class="table">
                <tr>
                    <td>
                        <strong>@role.Name | </strong> @Html.ActionLink("Renomear", "Edit", new { roleName = @role.Name }, new { @class = "btn btn-info btn-xs" }) | <span onclick="return confirm('Tem certeza que você deseja deletar?')"><a class="btn btn-info btn-xs" href="/Role/Delete?RoleName=@role.Name">Excluir</a></span> |
                    </td>

                </tr>
            </table>
        }
    </div>
</div>

PortoAlegrePlus/Views/Role/ManageUserRoles.cshtml
@{
    ViewBag.Title = "Grupo de Usuários";
}

<div class="container body-content">
    <h2>Gerenciar Grupo de Usuários</h2>

    @Html.ActionLink("Grupos de Usuários", "Index", null, new { @class = "btn btn-success" }) @Html.ActionLink("Criar Grupo de Usuários", "Create", null, new { @class = "btn btn-success" })
    <hr />

    <h4>Adicionar usuário para um Grupo</h4>

    @using (Html.BeginForm("RoleAddToUser", "Role"))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <form class="form-inline">
            <div class="form-group">
                <label>Email</label>
                @Html.TextBox("UserName", null, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "Selecione ...", new { @class = "btn btn-default dropdown-toggle" })
            </div>
            <button type="submit" class="btn btn-success">Adicionar</button>
        </form>

        @Html.Raw(TempData["add"])
    }

    <hr />
    <h4>Grupos que o usuário pertence</h4>
    @using (Html.BeginForm("GetRoles", "Role"))
            {
        @Html.AntiForgeryToken()

        <form>
            <div class="form-group">
                <label>E-mail</label>
                @Html.TextBox("UserName", null, new { @class = "form-control" })
            </div>

            <button type="submit" class="btn btn-success">Pesquisar</button>
        </form>

        @Html.Raw(TempData["get"])
    }

    <br />

    @if (ViewBag.RolesForThisUser != null)
    {
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">Grupos</h3>
            </div>
            <div class="panel-body">
                <ol>
                    @foreach (string s in ViewBag.RolesForThisUser)
                    {
                        <li>@s</li>
                    }
                </ol>
            </div>
        </div>
    }

    <hr />
    <h4>Remover usuário de um Grupo</h4>

    @using (Html.BeginForm("DeleteRoleForUser", "Role"))
            {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <form>
            <div class="form-group">
                <label>E-mail</label>
                @Html.TextBox("UserName", null, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "Selecione ...", new { @class = "btn btn-default dropdown-toggle" })
            </div>

            <button type="submit" class="btn btn-success">Remover</button>
        </form>

        @Html.Raw(TempData["delete"])

    }
</div>


